backend:
  name: git-gateway
  branch: main

site_url: https://begripassen.nl
display_url: https://begripassen.nl
logo_url: /images/logo.svg

media_folder: static/images/uploads
public_folder: /images/uploads

slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: events
    label: Evenementen
    label_singular: Evenement
    folder: content/events
    create: true
    extension: md
    format: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} - {{date}}"
    fields:
      - label: Titel
        name: title
        widget: string
      - label: Datum
        name: date
        widget: date
        date_format: YYYY-MM-DD
      - label: Tijd
        name: time
        widget: string
        required: false
      - label: Organisator
        name: organiser
        widget: string
        required: false
      - label: Locatie
        name: location
        widget: string
        required: false
      - label: Coverafbeelding
        name: image
        widget: image
        required: false
      - label: Aanmeldknop tonen
        name: show_signup
        widget: boolean
        default: false
        required: false
      - label: Aanmeldknop URL
        name: signup_link
        widget: string
        required: false
      - label: Inhoud
        name: body
        widget: markdown

  - name: blogs
    label: Blogs
    label_singular: Blog
    folder: content/blogs
    create: true
    extension: md
    format: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{author}} - {{date}}"
    fields:
      - label: Publicatiedatum
        name: date
        widget: datetime
        date_format: YYYY-MM-DD
        time_format: HH:mm
        format: YYYY-MM-DDTHH:mm:ssZ
      - label: Auteur
        name: author
        widget: string
        required: false
      - label: Uitgelichte afbeelding
        name: image
        widget: image
        required: false
      - label: Inhoud
        name: body
        widget: markdown
